### ISSUE TITLE
难题题面标准

### ISSUE THREAD

**Issue by buaabarty** [Jisuanke/tech-exp#10]
### 文字统一要求

1 参考 https://github.com/Jisuanke/tech-exp/issues/7
1.1 特别指出：题面中不要用『』，使用“”替代。
### 题干

1 图片居中，不要带其他 logo 或水印。
2 题面中的变量不要标明数据范围。数据范围留在输入格式中标明。
3 代码写在代码框内，不要以纯文本出现。
### 输入格式

1 格式参考 http://nanti.jisuanke.com/t/430
2 输入格式第一行为一行加粗的“输入格式”（去掉引号）。
3 接下来若干段文字：

3.1 如果有数据组数，则第一段讲输入格式，第二段讲每组数据的格式。
3.2 如果为单组数据，则统一到一段。
3.3 如果有一些特殊说明的内容（比如“数据保证合法”），另起一段。

4 输入格式中需要指明第几行输入几个元素，并指名每个元素的意义（比如长度）、类型（比如非负整数）和数据范围。数据范围使用括号中不等号来表示（1 ≤ n ≤ 100），而非省略号（n 的范围为 [ 1 .. 100 ]）或其他形式。
5 如果一个元素的行数或在一行中是第几列需要根据输入变量指定，则用变量组成的表达式表述。比如：『从第 2 行到第 T + 1 行』。
### 输出格式

1-5 同输入格式。第一行为一行加粗的“输出格式”（去掉引号）。
6 如果是 special judge，要在段后加一句：『如果有多组正确解，输出任意一组即可』。
7 如果有超过 int 或 longint 范围的可能，而题目又保证不超过，需要特别指出。比如“保证最终的解 ans 不会超过 32 位整型范围”。
### 数值及运算符

1 不等号：如果是小于等于或大于等于，使用 ≤ 而非 <=。
2 上下标：如果是 2 的若干次方，使用上标 2<sup>10</sup> 而非 2^10。
3 数组元素：用下标 a<sub>i</sub> 而非方括号 a[i] 或 Ai。
4 大数字：数字过大用x<sup>y</sup>替换，如 1000000000 替换为 10<sup>9</sup>。用来 hash 的大质数不用替换。

**Comment by JasinYip** [comment]
感觉这个可以转 wiki 了……

**Comment by buaabarty** [comment]
转到wiki了，以后有修改再说，issue先关了……
